### ISSUE TITLE
Input format finalized?

### ISSUE THREAD

**Issue by aggsol** [lifelike/gamebookformat#5]
Hwo does the input format look like and when is it ready?

**Comment by lifelike** [comment]
I am not sure much more will happen with this project, because of lack of interest and lack of myself even using it to write anything serious so far.

Even to use it now, I would recommend going back a few revisions on master branch, because merging the json branch broke the html/javascript export.

Not 100 % happy about the input format. For simple books it works, but when there are different tags affecting other tags (if you look at how requirements are added to links for instance) they have weird dependencies left-to-right that only works if the text is written in a certain way and does not work well if you try to write in a different way, and probably does not work well in all languages.

**Comment by aggsol** [comment]
I use a subset of Asciidoc with my own tooling now which works so far very. I get HTML and docbook formats that way and from there I can create everything else. I will maybe look at your Twine2 output at some point as I would love to have that too.

**Comment by lifelike** [comment]
Yes, like issue #1 said I got a bit carried away adding output formats and formatting instead of focusing on the useful stuff. Tools like pandoc and org-mode already do all the output that is useful. Graphviz output might make sense, but could be done with special code instead of abusing a more generic template system that is too flexible to be very good for anything.

**Comment by aggsol** [comment]
I added Graphviz output as the very first feature for my tool as it helped me writing the actual story a lot.
